### ISSUE TITLE
Ошибка с ng-view

### ISSUE THREAD

**Issue by ash-developer** [kaban4ik1994/SHUI#1]
В главном шаблоне директива ngView вставлена в 2-ух местах, поэтому все контроллеры выполняются по 2 раза. Это происходит, потому что директивы ngShow и ngHide не убирают элемент, а всего лишь добавляют css свойство display: none. Для того, что контроллеры выполнялись всего один раз, нужно использовать директиву ngIf.

**Comment by kaban4ik1994** [comment]
Да, спасибо:)
